### PR TITLE
Add marker for runs that broke the world record

### PR DESCRIPTION
**Pull request by williewillus**
Add marker for runs that broke the world record

It's easy to see people who LNN live, but not easy to see which people WR-ed live, which
is a cool datapoint to record.

Currently has:
* 2021: Borealis and pingval's WR's
* 2022: RB's WR
* 2023: RB's WR

There's probably other ones I missed, so let me know.

### CODE REVIEW

**Comment by williewillus** [comment]
Untested bc the site doesn't run properly for me locally, so will need someone else to help test.
Also, no idea how translations work.

**Comment by williewillus** [comment]
added translations

**Comment by 32th-System** [comment]
sorry but it's been really long since this PR and so much has changed about how the site works that it's prolly best to redo this PR another time. Heck, not even those JSON files exist anymore. It's all in a database now.

Basically: is it OK to just close this?

**Comment by williewillus** [comment]
Sure, just hope the records are captured on the site going forward.

**Pull request closed without merging**
